### ISSUE TITLE
Question about partitions

### ISSUE THREAD

**Issue by Silverlight42** [Azure/azure-event-hubs-spark#220]
Is it possible to read from a specific partition only?

**Comment by Silverlight42** [comment]
Oh, my guess is...

```
override def namesAndPartitions: List[NameAndPartition] = {
    for (eventHubName <- ehParams.keySet;
         partitionId <- 0 until ehParams(eventHubName)("eventhubs.partition.count").toInt)
      yield NameAndPartition(eventHubName, partitionId)
  }.toList
```

I should attempt to modify that?

**Comment by Silverlight42** [comment]
Nevermind.

**Comment by sabeegrewal** [comment]
Hey there. Right now you can only read data from all partitions in an EventHubs instance. Can you give more details on your use case? 

If you'd like to avoid processing data in other partitions, you can have them simply "pass-through" Spark. This can be done with `mapPartitionsWithIndex`. If that something you're interested in, I can share a code sample with you. Let me know!

**Comment by sabeegrewal** [comment]
Hey, sure thing!

```scala
val mapped = rdd.mapPartitionsWithIndex(
  (idx, iter) => if (idx == 0) iter else Iterator()
)
```

Where `idx` is the index of the `RDDPartition` and `iter` is an iterator for the partition. This will drop everything but partition 0 from your RDD. Though, it isn't guaranteed that `RDDPartition 0` matches `EventHubsPartition 0`. So, you'll have to add some more logic to make sure you're keeping the correct partitions. 


```scala
val mapped = rdd.mapPartitionsWithIndex{
  (idx, iter) => {
    // logic to figure out which partitions to keep/drop
  }
}
```

**Comment by sabeegrewal** [comment]
Marking as closed - let me know if anything else comes up!

**Comment by Silverlight42** [comment]
Hi @sabeegrewal,

First of all, sorry for the super late reply.

Some context: We have an event hub with 4 partitions and one HDInsight cluster.

We're getting the messages from event hub just fine. For each message we get,  we're downloading a file from blob storage and then doing some processing on it. But this is taking too long.

We thought it would be possible to have 4 clusters and have them read messages from one specific partition each.

We're attempting to use the snippet you kindly provided but we are not sure how to make sure that RDDPartition X matches EHPartitionX.

Any ideas?

Thanks in advance.

**Comment by ytaous** [comment]
We also need this feature. Here's valid case: there's limit for each partition on each consumer group. If there are more than 5 concurrent jobs in spark, we are getting the exception - "Exceeded the maximum number of allowed receivers per partition in a consumer group which is 5." Since we can't add more concurrent jobs, to perform faster, the solution is to create more consumer groups, and create multiple spark apps, each would hit different consumer group on specific partition(s). For example, a 32 partitions of Eventhub (1 default consumer group) read by 5 concurrent spark jobs would be much much slower than 16 consumer groups, each assigned 2 partitions and read by 1 Spark app. So16 Spark apps, each has 5 concurrent jobs, total would be 80 concurrent jobs. 16x faster !!

**Comment by ytaous** [comment]
Thanks for your feedback. To clarify: without additional consumer group (just default), I can create only 5 concurrent jobs. But with 16 consumer groups (each consume only 2 partitions), I can create 16 Spark apps, each also runs with 5 concurrent jobs. The total number of receivers for both settings would be the same, 160. But number of concurrent jobs using 16 Spark apps on 16 consumer groups can be 80. In other words, instead of having one Spark app consume from 32 partitions, we could have one Spark app consume from 2 partitions only. Thus it would scale.

I am wonder if the same concept of PartitionRecevier could be part of your SDK in near future. 
https://github.com/Azure/azure-event-hubs-java/blob/master/azure-eventhubs/src/main/java/com/microsoft/azure/eventhubs/PartitionReceiver.java
