### ISSUE TITLE
Base64 decode column in options

### ISSUE THREAD

**Issue by drcrook1** [Azure/azure-event-hubs-spark#233]
Azure IoT Hub provides messages as base64 encoded json strings.  It would be great to have an option to decode that automatically into a structure.  The message package is placed into the "body" column

### Feature Request
If you're submitting a feature request, make sure these questions are being answered:
- What issue are you trying to solve? Access my IoT Hub data easily
- How do you want to solve it?  Have a configuration option
- What is your use case for this feature? Large scale iot analysis.

**Comment by sabeegrewal** [comment]
Hi David! Internally, IoTHub (and EventHubs) has the the body as a byte array. In the new version of the connector (coming out within the next couple weeks), the body will be converted to a UTF-8 String. Holding the schema fixed (i.e. the body is always a UTF8 string) keeps the connector light and straightforward, and, since a lot is changing in this upcoming release, we don't want to add a switch to change the schema on demand just yet. 

I'm going to mark this as closed for now - after you use the new connector, if you still want the automatic conversion to base64 encoding, just re-open this issue and we can revisit it :)

**Comment by rcarmo** [comment]
I'd love to have this changed as well. It causes a number of issues when doing streaming that require byzantine workarounds...
