### ISSUE TITLE
Obtaining Offset - getting ${o.fromOffset} ${o.untilOffset} from offsetRanges

### ISSUE THREAD

**Issue by reksomu371** [Azure/azure-event-hubs-spark#285]
- Actual behavior
 The offsetRanges class  missing fromOffset variable

final class OffsetRange(val nameAndPartition: NameAndPartition,
                        val fromSeqNo: SequenceNumber,
                        val untilSeqNo: SequenceNumber,
val preferredLoc: Option[String])

- Expected behavior

final class OffsetRange(val nameAndPartition: NameAndPartition,
                        val fromOffset: Long,
                        val fromSeqNo: SequenceNumber,
                        val untilSeqNo: SequenceNumber,
val preferredLoc: Option[String])

 The offsetRanges class should contain  fromOffset variable in-order to manage the offset by the user. Incase of setting the EventPosition based on the offset value, need to read the current offset from the RDD.

i.e. EventPosition.fromOffset("246812")  as given in the EventPosition Document.

Overall the documentation is causing confusion whether user will be able to mange the offset by storing to external storage like blob storage as seen in Kafka where the option of storing in zookeeper.

Please update the Spark Streaming + Event Hubs Integration Guide appropriately to give more clarity on managing the offset.

Request you to add test case for obtaining and saving the offset.

- Spark version
    Spark 2.3
- spark-eventhubs artifactId and version
    <artifactId>azure-eventhubs-spark_2.11</artifactId>
    <version>2.3.0</version>

**Comment by sabeegrewal** [comment]
Hey @reksomu371, the variable is named `fromSeqNo`. Sorry about that! I've updated the docs to make things clearer 👍 

You can store your `fromSeqNo`, `untilSeqNo`, and anything else in `OffsetRanges` to external storage. Then you can read from there on start. Because you're reading sequence numbers, you have to use `EventPosition.fromSequenceNumber`.   

Make sense? Let me know! I want the experience to be smooth, so I'm happy to continue updating the Integration Guide :) 

Thanks for taking the time!

**Comment by sabeegrewal** [comment]
Excellent news - thanks for the feedback. Open an issue (or join us on the gitter chat) if anything else comes up! Happy to help 👍
