### ISSUE TITLE
not getting events written to hub before starting of spark job

### ISSUE THREAD

**Issue by guruvonline** [Azure/azure-event-hubs-spark#453]
in my structured streaming i am reading from event hub. with below code, But i am only getting events that are written to event hub after my spark job has started. But if my spark job is stopped and events are written to eventhub, i don't get those events when i start my job.

``` spark.readstream()
.format("eventhubs")
.option("eventhubs.connectionString","mystring")
.option("consumerGroup","mygroup")
```

how can i handle below scenarios

- when first time my job starts, i should read from begning of event hub(all events). after that any restart of job should start from last event read.
- if needed how can i reflow/re read again from start of event hub. Where does connector store it's state,  can i delete that storage location to make it start from starting of stream.

**Comment by basilhariri** [comment]
This is expected behavior as outlined in the [structured streaming doc](https://github.com/Azure/azure-event-hubs-spark/blob/master/docs/structured-streaming-eventhubs-integration.md#user-configuration).

Connector doesn't store any state about where you left off - that is handled by the Event Hubs service using our standard [consumer group semantics](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-features#consumer-groups). If you want to start over, use a new consumer group.

**Comment by guruvonline** [comment]
As suggested i tried  creating new consumer group, but it is failing with 
"java.lang.IllegalStateException: {"ehName":"eh2","partitionId":0} doesn't have a fromSeqNo"

my scearnio
My job connected to eventhub EH 1, then i changed my eventhub and connected to EH2, with a new consumergroup name. now When i start my job it fails with above message.
