### ISSUE TITLE
Databricks: com.microsoft.azure: azure-eventhubs-spark_2.12:2.3.17: not found

### ISSUE THREAD

**Issue by lycenok** [Azure/azure-event-hubs-spark#549]
The library cannot be installed.
![image](https://user-images.githubusercontent.com/31871647/97250317-cf0fb080-1859-11eb-8123-e3c57441c082.png)

 I can find it in central repostitory
https://mvnrepository.com/artifact/com.microsoft.azure/azure-eventhubs-spark 

Bug Report:

- Actual behavior: the library installation fails with the error in the issue subject
- Expected behavior: the library should be installed 
- Databricks Runtime: 6.6 (includes Apache Spark 2.4.5, Scala 2.11)
-  I tried these coordinates: 
com.microsoft.azure:azure-eventhubs-spark_2.12:2.3.17
com.microsoft.azure:azure-eventhubs-spark_2.12:2.3.16
com.microsoft.azure:azure-eventhubs-spark_2.11:2.3.17
com.microsoft.azure:azure-eventhubs-spark_2.11:2.3.16

**Comment by alexott** [comment]
You most probably hit the #539 for 2.3.17. You shouldn't use `_2.12` version with DBR 6.6, because it's Scala 2.11 based. I just created DBR 6.6 cluster with `com.microsoft.azure:azure-eventhubs-spark_2.11:2.3.16` and it works just fine.  Try to uninstall failed libraries, restart the cluster to get rid of the downloaded jars, and then install `com.microsoft.azure:azure-eventhubs-spark_2.11:2.3.16`
