### ISSUE TITLE
Question: Is EventHubsUtils.createDirectStream working for PySpark? 

### ISSUE THREAD

**Issue by mingsqtt** [Azure/azure-event-hubs-spark#589]
I am trying to use EventHubsUtils.createDirectStream(ssc, ehConf) to create a direct stream. The method reports AttributeError: 'StreamingContext' object has no attribute '_get_object_id'. When trying to EventHubsUtils.createDirectStream(ssc._jssc, ehConf) instead, the error message becomes py4j.Py4JException: Method createDirectStream([class org.apache.spark.streaming.api.java.JavaStreamingContext, class java.util.HashMap]) does not exist.

**Comment by nyaghma** [comment]
The [createDirectStream(JavaStreamingContext, EventHubsConf)](https://github.com/Azure/azure-event-hubs-spark/blob/b7f45554aa3a7c732d9e85e9745ae49c2dcd846e/core/src/main/scala/org/apache/spark/eventhubs/EventHubsUtils.scala#L95) method expects an 'EventHubsConf' object. Therefore, you should create and pass an 'EventHubsConf' object to the createDirectStream instead of the configuration dictionary.
