### ISSUE TITLE
Streaming Event Hubs : checkpointLocation has no effect to read from the last used element ?

### ISSUE THREAD

**Issue by E-HO** [Azure/azure-event-hubs-spark#605]
Hi,

Is it possible to update the content of the doc and examples of the page "[structured-streaming-pyspark.md](https://github.com/Azure/azure-event-hubs-spark/blob/master/docs/PySpark/structured-streaming-pyspark.md#recovering-from-failures-with-checkpointing)" ?

Some documentations are mentioning that's "easy" to recover the messages sent to an "Event Hubs" if the service is stopped, however after many tests it seems a bit "complicated".

The usual technique mentioned to be used for this is .option("checkpointLocation", "/CheckpointFolderPath")` ... but making something like the following code only take the new events since the query start, but not messages that have been send during the shutdown of this script, so actually events are lost : 

> df = spark \
>  .readStream \
>  .format("eventhubs") \
>  .options(**ehConf) \
>  .option("checkpointLocation", "/FileStore/CheckPoint/") \
>  .load()

Obviously, as descibed correctly, a possibility is to add a "startingEventPosition" object in the config, however it's not simple to guess by hand what could be the "offset" or "seqNo" to use (dozens of offset files are present) and this don't seems to consider the checkpointLocation technique !? That in order to avoid to recover and re-read all the messages available in events but who have already been processed.

Regards,

**Comment by nyaghma** [comment]
I'm not sure if I understand your concern correctly. The library integrates [Spark's checkpointing mechanism](https://spark.apache.org/docs/latest/structured-streaming-programming-guide.html#recovering-from-failures-with-checkpointing). As has been discussed in the shared document, the checkpoint location can be set as an option in the DataStreamWriter when starting a query. By using the checkpoint option, Spark saves the progress of the stream, and in case of failure, it recovers the stream from the last saved point. Also, when checkpointing is being used and a checkpoint is available, the library uses the positions in the latest checkpoint rather than using the "startingEventPosition" config.
Using the checkpointing option only affects where to start the stream during recovery and any messages that have not been processed (and committed) before the failure will be processed after recovery (as long as they are still available in the service).

**Comment by E-HO** [comment]
Maybe did I something wrong!? In fact this should be simple but sometimes the simplest things are not possible, so created my doubts and question because finally all examples using "checkpoint" are mentioned after writestream() only, event on [pyspark doc](https://spark.apache.org/docs/latest/structured-streaming-programming-guide.html).

With the simplest code wrote above, the streaming process is running but it takes only the NEW events that are coming, and no the old one who arrived when the query was off. Folder is existing and many "offset/int_number" are created (normal to have up to 90 similar files ?).

The only way of getting older messages that haven't been received when I start the readStream() is to add a config like :
> startingEventPosition = {
>     "offset": None,                                                #not in use
>     "seqNo": int_of_a_previous_message,              # -1 = not in use
>     "enqueuedTime": None,                                  #not in use
>     "isInclusive": True
> }
... but that's, as said, is not using the advantages of the "checkpointLocation" option, getting the correct "seqNo" or "offset" being not easy with the amount of files.

A "bug" elsewhere ?
- Databricks 8.1 : Spark 3.1.1, Scala 2.12
- Maven lib : com.microsoft.azure:azure-eventhubs-spark_2.12:2.3.18

Regards,

**Comment by nyaghma** [comment]
I think the problem in your case comes from the fact that you set the checkpoint when the stream is created (readStream) instead of when it is started (writeStream). As you can see in the Spark documentation the checkpointLocation is an option of writeStream. 
In your case, during the recovery Spark checks for a checkpoint location in DataStreamWriter, and since it can't find anything there it uses the "startingEventPosition" config to set the starting positions for the stream. Therefore, if you set the "startingEventPosition", it restarts the stream from the specified positions, otherwise, it restarts from the end of the stream which is the default value for the "startingEventPosition".
In order to fix this issue, you just need to set the checkpoint location as an option of "writeStream" instead of "readStream".

**Comment by E-HO** [comment]
Hum, so the automatic "checkpointLocation" is only for writes, and not for readings.
It's a pity , the missing point who could be useful however ...
